export const USER_DATA = 'USER_DATA';

export const GET_USER_DATA_INIT = 'GET_USER_DATA_INIT';
export const GET_USER_DATA_SUCCESS = 'GET_USER_DATA_SUCCESS';
export const GET_USER_DATA_ERROR = 'GET_USER_DATA_ERROR';
